spring:
  application:
    name: Football Manager

jwt:
  token:
    secret-key: ThisIsSecretKeyOfFootballManagerProjectThatHS512SignatureAlgorithmThatMUSTHave64ByteLengthForGeneratingJWT
    expiration-minutes: 480 # Minutes

security:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      key-length: 256